name: Generate Animations

on:
  schedule:
    - cron: "0 0 * * *" 
  workflow_dispatch:

jobs:
  generate:
    permissions: 
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 5
    
    steps:
      # 1. Snake Game Animation
      - name: generate-github-contribution-grid-snake
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark
          
      # 2. Updated 3D Graph (Official & Working Version)
      - name: generate-3d-graph
        uses: jasonlong/github-profile-3d-contrib@v0.7.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          USERNAME: ${{ github.repository_owner }}

      # 3. Push files to output branch
      - name: push files to output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
          keep_history: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
